name: Sync License Files

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  sync-license-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo (repositório consumidor)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}

      - name: Clone license repo
        run: git clone https://github.com/Valmir-de-Lima/license license-temp

      - name: Copy license files
        run: |
          cp license-temp/README.md .
          cp license-temp/LICENSE .
          cp license-temp/LICENSE.md .

      - name: Commit and push license files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md LICENSE LICENSE.md
          git diff --cached --quiet || git commit -m "Atualizando arquivos de licença automaticamente"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
